#配置端口号server:
server:
  port: 8080
  tomcat: #这个应该是配置中文乱码问题
    uri-encoding: UTF-8
#192.168.3.124:3306
spring:
  datasource: #配置数据库
    url: jdbc:mysql://localhost:3306/pms?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: jifen  #需要更改这三个属性！
    password: jifen123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
  http: #这个应该是配置中文乱码问题
      encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kaituo.pms.bean
  config-location: classpath:/sqlMapConfig.xml
#设置静态资源路径，多个以逗号分隔

